CREATE TABLE IF NOT EXISTS EMPLOYEE
(
    FULL_NAME VARCHAR,
    AGE       INT,
    SALARY    INT
);

INSERT INTO EMPLOYEE (FULL_NAME, AGE, SALARY)
VALUES ('Michael', 25, 1000),
       ('John', 30, 1500),
       ('Tom', 36, 2000);

SELECT FULL_NAME
FROM EMPLOYEE AS FULL_NAME;
SELECT AGE
FROM EMPLOYEE AS AGE;
SELECT SALARY
FROM EMPLOYEE AS SALARY;